//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebForms
{
    public partial class HackerNews
    {
        /// <summary>hfActiveTab control.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hfActiveTab;

        /// <summary>lblLiveBadge control.</summary>
        protected global::System.Web.UI.WebControls.Label lblLiveBadge;

        /// <summary>lblRefreshCountdown control.</summary>
        protected global::System.Web.UI.WebControls.Label lblRefreshCountdown;

        /// <summary>btnTabTop control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnTabTop;

        /// <summary>btnTabNew control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnTabNew;

        /// <summary>btnTabBest control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnTabBest;

        /// <summary>btnTabAsk control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnTabAsk;

        /// <summary>btnTabShow control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnTabShow;

        /// <summary>btnTabJobs control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnTabJobs;

        /// <summary>pnlMessage control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>litMessage control.</summary>
        protected global::System.Web.UI.WebControls.Literal litMessage;

        /// <summary>phStories control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phStories;

        /// <summary>pnlPager control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlPager;

        /// <summary>btnPrev control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnPrev;

        /// <summary>litPage control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPage;

        /// <summary>litPageCount control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPageCount;

        /// <summary>btnNext control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnNext;

        // ── Story detail panel ────────────────────────────────────────────────

        /// <summary>pnlStoryDetail control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlStoryDetail;

        /// <summary>btnCloseDetail control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnCloseDetail;

        /// <summary>litDetailTitle control.</summary>
        protected global::System.Web.UI.WebControls.Literal litDetailTitle;

        /// <summary>litDetailMeta control.</summary>
        protected global::System.Web.UI.WebControls.Literal litDetailMeta;

        /// <summary>pnlDetailText control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlDetailText;

        /// <summary>litDetailText control.</summary>
        protected global::System.Web.UI.WebControls.Literal litDetailText;

        /// <summary>pnlPollOptions control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlPollOptions;

        /// <summary>phPollOptions control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phPollOptions;

        /// <summary>litDetailCommentCount control.</summary>
        protected global::System.Web.UI.WebControls.Literal litDetailCommentCount;

        /// <summary>pnlCommentLoading control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlCommentLoading;

        /// <summary>phComments control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phComments;

        // ── User profile panel ────────────────────────────────────────────────

        /// <summary>pnlUserProfile control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlUserProfile;

        /// <summary>btnCloseUser control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnCloseUser;

        /// <summary>ucUserCard control.</summary>
        protected global::MyWebForms.HnUserCard ucUserCard;
    }
}
