// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace MyWebForms
{
    public partial class HnLive
    {
        // HnLive.aspx has no server-side controls that require code-behind
        // field declarations.  All interactivity is client-side JavaScript.
        // Visual Studio will keep this file empty unless runat="server"
        // controls are added to HnLive.aspx in future.
    }
}
