//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebForms
{
    public partial class LibraryStatusWidget
    {
        /// <summary>
        /// litLibraryName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLibraryName;

        /// <summary>
        /// litVersion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litVersion;

        /// <summary>
        /// progressBar control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl progressBar;

        /// <summary>
        /// lblStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatus;
    }
}
